stages:
  - codequality
  - build

flake8:
  image: python:3
  stage: codequality
  script:
    - pip install flake8 flake8-black pep8-naming flake8-bugbear
    - flake8 -v

zip:
  image: archlinux/base
  script:
    - pacman -Sy zip
    - zip -r dccsync.zip dccsync
  stage: build
  artifacts:
    paths:
      - dccsync.zip
    expire_in: 1 week