stages:
  - test
  - qa_build

flake8:
  tags:
    - linux
  image: python:3
  stage: qa_build
  script:
    - pip install flake8 flake8-black pep8-naming flake8-bugbear
    - flake8 -v

.zip:
  tags:
    - linux
  stage: qa_build
  script: exit 0
  artifacts:
    paths:
      - mixer
    expire_in: 1 week

zip:
  extends: .zip
  artifacts:
    name: "${CI_PROJECT_NAME}_${CI_COMMIT_MESSAGE}"

zip_release:
  only:
    - release
  extends: .zip
  artifacts:
    name: "${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}"

# https://gitlab-ncsa.ubisoft.org/help/ci/yaml/README.md
unittest:
  stage: test
  tags:
    - blender
  variables:
    MIXER_BLENDER_EXE_PATH: D:\gitlab_runner\blender-2.82a-windows64\blender.exe
    MIXER_BLENDER_EXE_DIR: D:\gitlab_runner\blender-2.82a-windows64
  script:
    - gitlab\run_unittest.bat
