stages:
  - codequality
  - build

flake8:
  image: python:3
  stage: codequality
  script:
    - pip install flake8 flake8-black pep8-naming flake8-bugbear
    - flake8 -v

zip:
  stage: build
  artifacts:
    name: "${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}"
    paths:
      - dccsync
    expire_in: 1 week