stages:
  - test
  - qa_build

flake8:
  tags:
    - linux
  image: python:3
  stage: qa_build
  script:
    - pip install flake8 flake8-black pep8-naming flake8-bugbear
    - flake8 -v

.zip:
  tags:
    - linux
  stage: qa_build
  script: exit 0

zip:
  extends: .zip
  artifacts:
    name: "${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}"
    paths:
      - mixer
    expire_in: 1 week

zip_release:
  only:
    - release
  extends: .zip
  artifacts:
    name: "${CI_PROJECT_NAME}_${CI_COMMIT_MESSAGE}"
    paths:
      - mixer

# https://gitlab-ncsa.ubisoft.org/help/ci/yaml/README.md
unittest:
  stage: test
  tags:
    - blender
  variables:
    MIXER_BLENDER_ZIP_BASENAME: blender-2.82a-windows64
    MIXER_BLENDER_VERSION_BASE: "2.82"
    MIXER_BASH_EXE: C:\Program Files\Git\bin\bash.exe
  script:
    - gitlab\run_unittest.bat
  cache:
    paths:
      - gitlab/blender/cache
