# a single stage allows test to run even if flake8 fails,
# and makes it possible to get all the errors at once
stages:
  - test
  - qa_build

flake8:
  tags:
    - linux
  image: python:3
  stage: qa_build
  script:
    - pip install flake8==3.7.9 flake8-black pep8-naming flake8-bugbear
    - flake8 -v

zip_release:
  only:
    refs:
      - /^v[0-9]+.[0-9]+.[0-9]+$/
  tags:
    - linux
  stage: qa_build
  script:
    - cp CHANGELOG.md README.md mixer/
  artifacts:
    name: "${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}"
    paths:
      - mixer
    expire_in: 42 yrs

zip:
  except:
    refs:
      - tags
  tags:
    - linux
  stage: qa_build
  script:
    - cp CHANGELOG.md README.md mixer/
  artifacts:
    name: "${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}"
    paths:
      - mixer
    expire_in: 1 week

# https://gitlab-ncsa.ubisoft.org/help/ci/yaml/README.md
unittest:
  stage: test
  tags:
    - blender
  variables:
    MIXER_BLENDER_ZIP_BASENAME: blender-2.82a-windows64
    MIXER_BLENDER_VERSION_BASE: "2.82"
    MIXER_BASH_EXE: C:\Program Files\Git\bin\bash.exe
  script:
    - gitlab\run_unittest.bat
  cache:
    paths:
      - gitlab/blender/cache
