stages:
  - codequality
  - test
  - build

flake8:
  tags:
    - linux
  image: python:3
  stage: codequality
  script:
    - pip install flake8 flake8-black pep8-naming flake8-bugbear
    - flake8 -v

zip:
  tags:
    - linux
  stage: build
  script: exit 0
  artifacts:
    name: "${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}"
    paths:
      - dccsync
    expire_in: 1 week

# https://gitlab-ncsa.ubisoft.org/help/ci/yaml/README.md
unittest:
  stage: test
  tags:
    - blender
  variables:
    DCCSYNC_BLENDER_EXE_PATH: D:\gitlab_runner\blender-2.82a-windows64\blender.exe
    DCCSYNC_BLENDER_EXE_DIR: D:\gitlab_runner\blender-2.82a-windows64
  script:
    - gitlab\run_unittest.bat

# During early development, easier to keep track of failures with a separate step. Merge later in previous step
unittest-blenddata:
  stage: test
  tags:
    - blender
  variables:
    DCCSYNC_BLENDER_EXE_PATH: D:\gitlab_runner\blender-2.82a-windows64\blender.exe
    DCCSYNC_BLENDER_EXE_DIR: D:\gitlab_runner\blender-2.82a-windows64
  script:
    - gitlab\run_unittest_blenddata.bat
